DROP TABLE if exists hotels;

CREATE TABLE `hotels`(`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`image_URL` VARCHAR(255) NOT NULL,
`name` VARCHAR(255) NOT NULL,
`location` VARCHAR(255) NOT NULL,
`description` TEXT NULL,
`price_range` VARCHAR(255) NOT NULL,
`yoga` tinyint NOT NULL,
`spa` tinyint NOT NULL, PRIMARY KEY(`id`));

INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.reinavictoriaalicante.com/lib/timThumb/timThumb.php?src=/upload/images/habitacion_402-10.jpg&w=607&h=287&zc=1', 'Reina Victoria La PlazaOpen', 'Alicante','Set in Alicante, Reina Victoria La Plaza offers accommodation with free WiFi, city views, and access to a hot tub. The accommodation features a hot tub and a spa bath.', 'budget', 0, 1);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/295469529.jpg?k=133bd4aab3f79b30bb4c34dfbcd84dd202cd5d5d60b301b68ebe02798e3dbd44&o=&hp=1', 'Hotel Smile & Co Hostal Boutique', 'Alicante', 'Featuring free WiFi throughout the property, Hotel Smile & Co Hostal Boutique offers accommodation with a bar and private parking. Each room includes a flat-screen TV and air conditioning.', 'budget', 0, 0);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://content.r9cdn.net/rimg/kimg/68/2a/8fca1bb0-617123c7-41.jpeg?width=500&height=350&xhint=1122&yhint=793&crop=true', 'Hotel Spa Porta Maris', 'Alicante', '200 m from the Postiguet beach and very close to the marina and the historic city centre, this urban hotel combines the main attractions for a stay in Alicante. Rooms with sea views. A fun and varied gastronomic option. Pool and terrace with solarium also overlooking the Mediterranean. And a modern and equipped 400 m2 spa for pure relaxation.', 'budget', 0, 1);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.hoteltossalaltea.com/wp-content/uploads/2018/03/Habitacion-doble-matrimonial-double-room-Hotel-Tossal-Altea-1.jpg', 'Hotel Tossal Altea', 'Alicante', 'Hotel Tossal Altea is a traditional hotel and gastronomic establishment located on a 300-year-old olive oil mill in Altea. So, this historic building has been restored and it was a farmhouse and a farm of olive, almond and orange trees known as “Almàssera de Guillem”.', 'mid range', 1, 0);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.masqi.es/album/habitaciones/FH-namaste-02.jpg?123', 'MasQi The Energy House', 'Alicante', 'From MasQi we propose a way of learning to live life in a healthier way - fuller, more consciously and calmer. To do this, we will help you to find inspiration and strength, providing you with tools through the practice of yoga, meditation, bio-energetic therapies, mentoring or Ayurveda. All this surrounded by the natural environment of the Sierra de Mariola.', 'mid range', 1, 1);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/12167665.jpg?k=1a42f992de7008b61e3bb0602672af314df1274b08ea1238b02ad9547aa07b33&o=&hp=1', 'Asia Gardens Hotel and Thai Spa', 'Alicante', 'Many famous faces have chosen Asia Gardens Hotel & Thai Spa to enjoy a unique escape. This exclusive hotel with all the serenity, peace and quiet of South-East Asia is a member of Leading Hotels of the World, guaranteeing complete relaxation and perfect service. Its lush tropical gardens with more than 3,000 species brought from Asia, its 7 spectacular swimming pools, 5 of which are heated, the choice of 9 exclusives restaurants, a Thai Spa where one can lose all sense of time and regain vital energy, are just a few of the reasons…', 'luxury', 0, 1);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/28127072.jpg?k=1154371d576d03c9bd4296aa5c494ad1b14bad48f061d9b496a2ee345a8152d6&o=&hp=1', 'Abalú Boutique & Design Hotel', 'Madrid','Ab Design Suites Madrid are spacious apartments and suites between 40 and 90 m². Located in the Madrid neighborhood of Malasaña considered the Soho of the city. The apartments are surrounded by designer boutiques, a restaurant area, tapas... The best option to stay two steps from Gran Vía.', 'budget', 0, 1);    
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max500/330747190.jpg?k=2340dcb141db67b90d60a0153142715c3c9352e3f3c9912f5e2572c910b59a83&o=&hp=1', 'Bob W Chueca', 'Madrid','Located in the center of Madrid, 500 meters from Gran Vía Metro Station and 600 meters from Gran Vía, Bob W Chueca offers accommodation with free WiFi and seating area. All accommodations have a private bathroom with a shower, air conditioning, a flat-screen TV and a fridge. There is a microwave, toaster and kettle.', 'budget', 0, 0);  
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.theprincipalmadridhotel.com/content/imgsxml/blog/eat-drink_la-terraza.jpg', 'The Principal Madrid', 'Madrid','A gem in the shape of a hotel. This extraordinary property combines city leisure and the privacy and comfort of a home away from home. Within the walls of this fortress, you will find all the finesse and attention to detail that celebrates elegance and exclusivity. Being the first 5-star hotel in Gran Via.', 'luxury', 1, 1);    
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/d8/71/db/the-green-lounge-bar.jpg?w=700&h=-1&s=1', 'ARTIEM Madrid', 'Madrid','The ARTIEM Madrid **** hotel is perfect for disconnecting from the hustle and bustle of the capital, practicing sports, getting inspired to work or holding a meeting. Make yourself at home in the renovated space of The Green, a welcoming place that transforms during the day to suit your needs, or clear your mind with a workout in the new gym.', 'mid range', 1, 1);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/99/7d/5c/room-mate-mario-hotel.jpg?w=700&h=-1&s=1', 'Room Mate Mario', 'Madrid','This design hotel is located in central Madrid, just off Ópera Square and 200 metres from the Royal Palace. It offers stylish rooms with avant-garde design, free Wi-Fi and satellite TV. The ultra-modern rooms at Room Mate Mario are equipped with air conditioning, heating and a flat-screen TV.', 'budget', 1, 0);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://hotelcasa.nl/wp-content/uploads/2022/09/Casa_Lobby-EAST-251.jpg', 'Hotel Casa', 'Amsterdam','Casa is all about coming home and getting that comfy, homely feeling in our bright and spacious rooms. You will find yourself a king size bed in every hotel room, with a desk, fridge, cozy windowsill seat, coffee and tea, a safe, extra pillows, and a relaxed shower - just like home. Up for something extra? Then go for our Premium room, with great views over Amsterdam East, extra amenities, a bathrobe, and slippers. A fresh color palette awaits you in all of our rooms, as well as beautiful fabrics and dimmable lighting to create an ambiance just to your taste.', 'mid range', 1, 0);      
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/21/34/e6/king-junior-suite.jpg?w=700&h=-1&s=1', 'Kimpton De Witt Amsterdam', 'Amsterdam','Experience an immersive array of contemporary millwork, lush layers and clean lines. A journey where rooms open to grand inspiration and eclectic treasures. Nestled in the heart of Amsterdam’s thriving City Centre, our hotel inspires you to imagine, explore, create and find a comfortable place to relax.', 'luxury', 1, 1);           
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.boatandco.nl/upload/images/family-apartment-800x400_1.jpg', 'Hotel BOAT & CO', 'Amsterdam','We are BOAT&CO, an apartment hotel at the waterfront in the Amsterdam Houthaven. You’ll find us close to the historic city centre, in an up and coming area full of design, good food and forward-thinking entrepreneurs. Hotspots like the Westerpark and the Jordaan are just a bike-ride away.', 'mid range', 1, 1);           
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/21/34/e6/king-junior-suite.jpg?w=700&h=-1&s=1', 'Hotel Hotel', 'Lisbon','As much a social center as a hotel, this Lisbon renegade brings creative locals to the forefront, connecting the visitor to the pulse of the city and the neighborhood.', 'luxury', 1, 0);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://static.wixstatic.com/media/6e1dec_26ffb33ef8b14a1cab5abb743d6634db~mv2.jpg/v1/crop/x_0,y_435,w_3000,h_2144/fill/w_1225,h_875,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Welcome%20Lobby%20Light_edited.jpg', 'toctoctoc lisboa', 'Lisbon', 'Nestled between the famous Estrela gardens, the Sao Bento street famous for its antique dealers, and the charming Praça das Flores, toctoctocLisboa is a secret and peaceful haven in the heart of Lisbon. Behind the traditional facade of azulejos and flower-covered balconies hide 10 rooms situated around a patio and a silent garden. Each room has been decorated in a unique style and with souvenir objects from numerous trips.', 'luxury', 1, 0);           
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.santjordihostels.com/wp-content/uploads/8bed_female_ensuite.jpg', 'Sant Jordi Hostels Lisbon', 'Lisbon','Sant Jordi Hostels Lisbon is an elegant and modern hostel, very close to the center of Lisbon, which you can reach quickly with just a ride on its iconic trams. You will be amazed by the building built at the beginning of the 20th century, its majestic essence combined with modern comforts for your enjoyment. You will find a large garden, terraces, an incredible bar and rooms prepared for rest. With its warm and welcoming atmosphere, Sant Jordi Hostels Lisbon is the ideal place to relax between adventures.', 'budget', 1, 0);           
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.thevintagelisbon.com/wp-content/uploads/2019/08/vintage-delux-landscape-1-1196x679.jpg', 'The Vintage Hotel & Spa Lisbon', 'Lisbon','Situated only a 10-minute bike ride from the city centre, The Social Hub Amsterdam West offers fully furnished rooms with free Wi-Fi. Metro station Jan van Galenstraat is only 100 metres away with direct links to RAI, Zuid WTC and Bijlmer Arena.', 'mid range', 0, 1);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/260849625.jpg?k=ea423e44ddbbbd4e5e7d01389bb52b79ab2413885e14c91d4dc88ed51515a667&o=&hp=1', 'Aspria Berlin Ku damm', 'Berlin','An urban retreat spread over six floors. The largest club of its kind in Europe, right in the heart of Berlin. Expansive training areas, an indoor pool and personalised fitness programmes created by expert trainers. Work and connect, unwind on the rooftop terrace or escape in the award-winning spa.', 'mid range', 1, 1);   
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.amanogroup.de/wp-content/uploads/2016/06/amanogroup_hotels_amanohome_top_1.jpg', 'AMANO HOME Apartments', 'Berlin','AMANO Home is located at one of Berlin’s most exciting crossroads: Torstraße, Schönhauser Allee, and Alte Schönhauser Straße. The Berlin Cathedral is just a ten-minute walk away. Fancy some art galleries for every taste? This is the district that will fill up all those cravings. Berlin’s trendiest restaurants are right on your doorstep. Shopping? Flagship Scandinavian stores, retailers, and bold Berlin labels await just around the corner. - always the best price guaranteed on amanogroup.de', 'luxury', 1, 0);   
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.thevintagelisbon.com/wp-content/uploads/2019/08/vintage-delux-landscape-1-1196x679.jpg', 'Townhouse Berlin', 'Berlin','47 studios and suites, each room with a special flair. Large windows let plenty of light into the rooms. Free high-speed Wifi and a fully equipped kitchen are also part of the facilities. View: city or garden - your choice. In addition, a launderette, a fitness area equipped with Hammer Strength and LifeFitness equipment, a shopping service for all guests in rooms with fully equipped kitchens.', 'luxury', 0, 1);   
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.visitberlin.de/system/files/styles/visitberlin_bleed_header_visitberlin_mobile_1x/private/image/mowuestenhagen_visitberlin_01_CircusHotel_047_web.jpg?h=1c9b88c9&itok=x35chrOM', 'The Circus Hotel', 'Berlin','The Circus Hotel is a boutique, design-orientated hotel in Berlin-Mitte, housed in a beautifully restored 19th-century landmark-protected building overlooking Rosenthaler Platz. Close to all the main attractions of the city and in a lively neighbourhood of bars, restaurants, art galleries and independent shops, we’re here to help you experience all that Berlin has to offer.', 'budget', 1, 1);                         