DROP TABLE if exists hotels;

CREATE TABLE `hotels`(`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`image_URL` VARCHAR(255) NOT NULL,
`name` VARCHAR(255) NOT NULL,
`location` VARCHAR(255) NOT NULL,
`description` TEXT NULL,
`price_range` VARCHAR(255) NOT NULL,
`yoga` tinyint NOT NULL,
`spa` tinyint NOT NULL, PRIMARY KEY(`id`));

INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.reinavictoriaalicante.com/lib/timThumb/timThumb.php?src=/upload/images/habitacion_402-10.jpg&w=607&h=287&zc=1', 'Reina Victoria La PlazaOpen', 'Alicante','Set in Alicante, Reina Victoria La Plaza offers accommodation with free WiFi, city views, and access to a hot tub. The accommodation features a hot tub and a spa bath.', 'budget', 0, 1);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/295469529.jpg?k=133bd4aab3f79b30bb4c34dfbcd84dd202cd5d5d60b301b68ebe02798e3dbd44&o=&hp=1', 'Hotel Smile & Co Hostal Boutique', 'Alicante', 'Featuring free WiFi throughout the property, Hotel Smile & Co Hostal Boutique offers accommodation with a bar and private parking. Each room includes a flat-screen TV and air conditioning.', 'budget', 0, 0);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/295469529.jpg?k=133bd4aab3f79b30bb4c34dfbcd84dd202cd5d5d60b301b68ebe02798e3dbd44&o=&hp=1', 'Hotel Smile & Co Hostal Boutique', 'Alicante', 'Featuring free WiFi throughout the property, Hotel Smile & Co Hostal Boutique offers accommodation with a bar and private parking. Each room includes a flat-screen TV and air conditioning.', 'budget', 0, 0);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.hoteltossalaltea.com/wp-content/uploads/2018/03/Habitacion-doble-matrimonial-double-room-Hotel-Tossal-Altea-1.jpg', 'Hotel Tossal Altea', 'Alicante', 'Hotel Tossal Altea is a traditional hotel and gastronomic establishment located on a 300-year-old olive oil mill in Altea. So, this historic building has been restored and it was a farmhouse and a farm of olive, almond and orange trees known as “Almàssera de Guillem”.', 'mid range', 1, 0);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://www.masqi.es/album/habitaciones/FH-namaste-02.jpg?123', 'MasQi The Energy House', 'Alicante', 'From MasQi we propose a way of learning to live life in a healthier way - fuller, more consciously and calmer. To do this, we will help you to find inspiration and strength, providing you with tools through the practice of yoga, meditation, bio-energetic therapies, mentoring or Ayurveda. All this surrounded by the natural environment of the Sierra de Mariola.', 'mid range', 1, 1);
INSERT INTO hotels (image_URL, name, location, description, price_range, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/12167665.jpg?k=1a42f992de7008b61e3bb0602672af314df1274b08ea1238b02ad9547aa07b33&o=&hp=1', 'Asia Gardens Hotel and Thai Spa', 'Alicante', 'Many famous faces have chosen Asia Gardens Hotel & Thai Spa to enjoy a unique escape. This exclusive hotel with all the serenity, peace and quiet of South-East Asia is a member of Leading Hotels of the World, guaranteeing complete relaxation and perfect service. Its lush tropical gardens with more than 3,000 species brought from Asia, its 7 spectacular swimming pools, 5 of which are heated, the choice of 9 exclusives restaurants, a Thai Spa where one can lose all sense of time and regain vital energy, are just a few of the reasons…', 'luxury', 0, 1);    