CREATE TABLE `hotels`(`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`image URL` VARCHAR(255) NOT NULL,
`name` VARCHAR(255) NOT NULL,
`location` VARCHAR(255) NOT NULL,
`description` TEXT NULL,
`price range` VARCHAR(255) NOT NULL,
`yoga` tinyint NOT NULL,
`spa` tinyint NOT NULL, PRIMARY KEY(`id`));

INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.reinavictoriaalicante.com/lib/timThumb/timThumb.php?src=/upload/images/habitacion_402-10.jpg&w=607&h=287&zc=1', 'Reina Victoria La PlazaOpen', 'Alicante','Set in Alicante, Reina Victoria La Plaza offers accommodation with free WiFi, city views, and access to a hot tub. The accommodation features a hot tub and a spa bath.', 'budget', 0, 1);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/295469529.jpg?k=133bd4aab3f79b30bb4c34dfbcd84dd202cd5d5d60b301b68ebe02798e3dbd44&o=&hp=1', 'Hotel Smile & Co Hostal Boutique', 'Alicante', 'Featuring free WiFi throughout the property, Hotel Smile & Co Hostal Boutique offers accommodation with a bar and private parking. Each room includes a flat-screen TV and air conditioning.', 'budget', 0, 0);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://content.r9cdn.net/rimg/kimg/68/2a/8fca1bb0-617123c7-41.jpeg?width=500&height=350&xhint=1122&yhint=793&crop=true', 'Hotel Spa Porta Maris', 'Alicante', '200 m from the Postiguet beach and very close to the marina and the historic city centre, this urban hotel combines the main attractions for a stay in Alicante. Rooms with sea views. A fun and varied gastronomic option.', 'budget', 0, 1);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.hoteltossalaltea.com/wp-content/uploads/2018/03/Habitacion-doble-matrimonial-double-room-Hotel-Tossal-Altea-1.jpg', 'Hotel Tossal Altea', 'Alicante', 'Hotel Tossal Altea is a traditional hotel and gastronomic establishment located on a 300-year-old olive oil mill in Altea. So, this historic building has been restored.', 'mid range', 1, 0);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.masqi.es/album/habitaciones/FH-namaste-02.jpg?123', 'MasQi The Energy House', 'Alicante', 'From MasQi we propose a way of learning to live life in a healthier way - fuller, more consciously and calmer.', 'mid range', 1, 1);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/12167665.jpg?k=1a42f992de7008b61e3bb0602672af314df1274b08ea1238b02ad9547aa07b33&o=&hp=1', 'Asia Gardens Hotel and Thai Spa', 'Alicante', 'Many famous faces have chosen Asia Gardens Hotel & Thai Spa to enjoy a unique escape. This exclusive hotel is a member of Leading Hotels of the World.', 'luxury', 0, 1);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/28127072.jpg?k=1154371d576d03c9bd4296aa5c494ad1b14bad48f061d9b496a2ee345a8152d6&o=&hp=1', 'Abalú Boutique & Design Hotel', 'Madrid','Ab Design Suites Madrid are spacious apartments and suites between 40 and 90 m². Located in the Madrid neighborhood of Malasaña considered the Soho of the city.', 'budget', 0, 1);    
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max500/330747190.jpg?k=2340dcb141db67b90d60a0153142715c3c9352e3f3c9912f5e2572c910b59a83&o=&hp=1', 'Bob W Chueca', 'Madrid','Located in the center of Madrid, 500 meters from Gran Vía Metro Station and 600 meters from Gran Vía, Bob W Chueca offers accommodation with free WiFi and seating area.', 'budget', 0, 0);  
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.theprincipalmadridhotel.com/content/imgsxml/blog/eat-drink_la-terraza.jpg', 'The Principal Madrid', 'Madrid','A gem in the shape of a hotel. This extraordinary property combines city leisure and the privacy and comfort of a home away from home. Within the walls of this fortress, you will find all the finesse.', 'luxury', 1, 1);    
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/d8/71/db/the-green-lounge-bar.jpg?w=700&h=-1&s=1', 'ARTIEM Madrid', 'Madrid','The ARTIEM Madrid **** hotel is perfect for disconnecting from the hustle and bustle of the capital, practicing sports, getting inspired to work or holding a meeting. Make yourself at home in the renovated space of The Green', 'mid range', 1, 1);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/99/7d/5c/room-mate-mario-hotel.jpg?w=700&h=-1&s=1', 'Room Mate Mario', 'Madrid','This design hotel is located in central Madrid, just off Ópera Square and 200 metres from the Royal Palace. It offers stylish rooms with avant-garde design, free Wi-Fi and satellite TV.', 'budget', 1, 0);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://hotelcasa.nl/wp-content/uploads/2022/09/Casa_Lobby-EAST-251.jpg', 'Hotel Casa', 'Amsterdam','Casa is all about coming home and getting that comfy, homely feeling in our bright and spacious rooms.', 'mid range', 1, 0);      
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/21/34/e6/king-junior-suite.jpg?w=700&h=-1&s=1', 'Kimpton De Witt Amsterdam', 'Amsterdam','Experience an immersive array of contemporary millwork, lush layers and clean lines. A journey where rooms open to grand inspiration and eclectic treasures. Nestled in the heart of Amsterdam’s thriving City Centre.', 'luxury', 1, 1);           
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.boatandco.nl/upload/images/family-apartment-800x400_1.jpg', 'Hotel BOAT & CO', 'Amsterdam','We are BOAT&CO, an apartment hotel at the waterfront in the Amsterdam Houthaven. You’ll find us close to the historic city centre, in an up and coming area full of design, good food and forward-thinking entrepreneurs.', 'mid range', 1, 1);           
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/21/34/e6/king-junior-suite.jpg?w=700&h=-1&s=1', 'Hotel Hotel', 'Lisbon','As much a social center as a hotel, this Lisbon renegade brings creative locals to the forefront, connecting the visitor to the pulse of the city and the neighborhood.', 'luxury', 1, 0);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://static.wixstatic.com/media/6e1dec_26ffb33ef8b14a1cab5abb743d6634db~mv2.jpg/v1/crop/x_0,y_435,w_3000,h_2144/fill/w_1225,h_875,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Welcome%20Lobby%20Light_edited.jpg', 'toctoctoc lisboa', 'Lisbon', 'Nestled between the famous Estrela gardens, the Sao Bento street famous for its antique dealers', 'luxury', 1, 0);           
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.santjordihostels.com/wp-content/uploads/8bed_female_ensuite.jpg', 'Sant Jordi Hostels Lisbon', 'Lisbon','Sant Jordi Hostels Lisbon is an elegant and modern hostel, very close to the center of Lisbon, which you can reach quickly with just a ride on its iconic trams.', 'budget', 1, 0);           
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.thevintagelisbon.com/wp-content/uploads/2019/08/vintage-delux-landscape-1-1196x679.jpg', 'The Vintage Hotel & Spa Lisbon', 'Lisbon','Situated only a 10-minute bike ride from the city centre, The Social Hub Amsterdam West offers fully furnished rooms with free Wi-Fi.', 'mid range', 0, 1);
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://cf.bstatic.com/xdata/images/hotel/max1024x768/260849625.jpg?k=ea423e44ddbbbd4e5e7d01389bb52b79ab2413885e14c91d4dc88ed51515a667&o=&hp=1', 'Aspria Berlin Ku damm', 'Berlin','An urban retreat spread over six floors. The largest club of its kind in Europe, right in the heart of Berlin. Expansive training areas and an indoor pool.', 'mid range', 1, 1);   
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.amanogroup.de/wp-content/uploads/2016/06/amanogroup_hotels_amanohome_top_1.jpg', 'AMANO HOME Apartments', 'Berlin','AMANO Home is located at one of Berlin’s most exciting crossroads: Torstraße, Schönhauser Allee, and Alte Schönhauser Straße. The Berlin Cathedral is just a ten-minute walk away. Fancy some art galleries for every taste?', 'luxury', 1, 0);   
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.thevintagelisbon.com/wp-content/uploads/2019/08/vintage-delux-landscape-1-1196x679.jpg', 'Townhouse Berlin', 'Berlin','47 studios and suites, each room with a special flair. Large windows let plenty of light into the rooms. Free high-speed Wifi and a fully equipped kitchen are also part of the facilities. View: city or garden - your choice.', 'luxury', 0, 1);   
INSERT INTO hotels (`image URL`, name, location, description, `price range`, yoga, spa) VALUES ('https://www.visitberlin.de/system/files/styles/visitberlin_bleed_header_visitberlin_mobile_1x/private/image/mowuestenhagen_visitberlin_01_CircusHotel_047_web.jpg?h=1c9b88c9&itok=x35chrOM', 'The Circus Hotel', 'Berlin','The Circus Hotel is a boutique, design-orientated hotel in Berlin-Mitte, housed in a beautifully restored 19th-century landmark-protected building', 'budget', 1, 1);  

CREATE TABLE `favourites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hotel_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`hotel_id`) REFERENCES `hotels` (`id`),
  
);